use_frameworks!

platform :ios, '10.0'

target 'IosAwnCore_Example' do
  pod 'IosAwnCore', :path => '../'

  target 'IosAwnCore_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
